name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: bjand49
        password: dckr_pat_yASEuxsKPk7fHiulHd7GJjjmnU8

    - name: Push Docker image
      run: docker push bjand49/dls:latest

